crops = ["BARLEY", "BEANS", "BUCKWHEAT", "CANOLA", "CORN", "COTTON", "FLAXSEED", "HAY", "HERBS", "HOPS", "LENTILS", "MAPLE SYRUP", "MILLET", "MINT", "OATS", "PEANUTS", "PEAS", "RICE", "RYE", "SAFFLOWER", "SORGHUM", "SOYBEANS", "SUNFLOWER", "TOBACCO", "WHEAT", "WILD RICE"]

# CROP, PRODUCTIONS, SALES
# BARLEY, YES, YES
# BEANS, YES, PARTIAL
# BUCKWHEAT, YES, PARTIAL
# CANOLA, YES, PARTIAL
# CORN, YES, YES
# COTTON, YES, YES
# FLAXSEED, YES, PARTIAL
# HAY, YES, PARTIAL
# HERBS, YES, PARTIAL
# HOPS, YES, PARTIAL
# LENTILS, YES, YES
# MAPLE SYRUP, YES, YES
# MILLET, YES, PARTIAL
# MINT, YES, PARTIAL
# OATS, YES, PARTIAL
# PEANUTS, YES, PARTIAL
# PEAS, YES, PARTIAL
# RICE, YES, YES
# RYE, YES, PARTIAL
# SAFFLOWER, YES, PARTIAL
# SORGHUM, YES, YES
# SOYBEANS, YES, YES
# SUNFLOWER, YES, PARTIAL
# TOBACCO, YES, PARTIAL
# WHEAT, YES, YES
# WILD RICE, YES, PARTIAL